# SPDX-FileCopyrightText: 2026 Andrew Grimberg <tykeal@bardicgrove.org>
# SPDX-License-Identifier: Apache-2.0

checkout:
  target:
    entity:
      integration: rental_control
      domain: sensor
  fields:
    force:
      required: false
      default: false
      selector:
        boolean:
