---
# SPDX-FileCopyrightText: 2026 Andrew Grimberg <tykeal@bardicgrove.org>
# SPDX-License-Identifier: Apache-2.0

# This workflow uses actions that are not certified by GitHub. They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.

name: 'OpenSSF Scorecard'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  # For Branch-Protection check. Only the default branch is supported. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  # To guarantee Maintained check is occasionally updated. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained
  schedule:
    - cron: '50 4 * * 0'
  push:
    branches: ['main']
    paths:
      - '**'
      - '!.github/**'

# Declare default permissions as none.
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  openssf-scorecard:
    name: 'OpenSSF Scorecard'
    # yamllint disable-line rule:line-length
    uses: lfit/releng-reusable-workflows/.github/workflows/reuse-openssf-scorecard.yaml@eb97ae44b0af065a905ddd74b7ac7416796c8554  # v0.9.0
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write  # Upload Scorecard results to code scanning.
      # Needed to publish results and get a badge (see publish_results).
      id-token: write  # Publish results and mint the badge.
