---
# SPDX-FileCopyrightText: 2021 Andrew Grimberg <tykeal@bardicgrove.org>
# SPDX-License-Identifier: Apache-2.0

# Validates integration against Home Assistant and HACS requirements
name: 'Validate'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  hassfest:
    name: 'Hassfest'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40  # v2.19.0
        with:
          egress-policy: 'audit'

      - name: 'Checkout repository'
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: 'Validate with hassfest'
        # yamllint disable-line rule:line-length
        uses: home-assistant/actions/hassfest@f6f29a7ee3fa0eccadf3620a7b9ee00ab54ec03b  # master (no tags published)

  hacs:
    name: 'HACS'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40  # v2.19.0
        with:
          egress-policy: 'audit'

      - name: 'Checkout repository'
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: 'Validate with HACS'
        # yamllint disable-line rule:line-length
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a  # v22.5.0
        with:
          category: 'integration'
