---
# SPDX-FileCopyrightText: 2021 Andrew Grimberg <tykeal@bardicgrove.org>
# SPDX-License-Identifier: Apache-2.0

# Validates integration against Home Assistant and HACS requirements
name: 'Validate'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  hassfest:
    name: 'Hassfest'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920  # v2.20.0
        with:
          egress-policy: 'audit'

      - name: 'Checkout repository'
        # yamllint disable-line rule:line-length
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: 'Validate with hassfest'
        # yamllint disable-line rule:line-length
        uses: home-assistant/actions/hassfest@f4ca6f671bd429efb108c0f2fa0ae8af0215986c  # master (no tags published)

  hacs:
    name: 'HACS'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920  # v2.20.0
        with:
          egress-policy: 'audit'

      - name: 'Checkout repository'
        # yamllint disable-line rule:line-length
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: 'Validate with HACS'
        # yamllint disable-line rule:line-length
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a  # v22.5.0
        with:
          category: 'integration'
